version: '3'

services:
  open-trade-gateway:
    image: opentradegateway
    build: .
    volumes:
      - ./docker/conf:/etc/open-trade-gateway
      - ./docker/user:/var/local/lib/open-trade-gateway
      - ./docker/log:/var/log/open-trade-gateway
      - ./:/usr/src/shinnytech/open-trade-gateway
    ports:
      - "7788:7788"
    expose:
      - "7788"
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        chmod +x "/usr/src/shinnytech/open-trade-gateway/run.sh" && "/usr/src/shinnytech/open-trade-gateway/run.sh"